package echoes.codejava.model;
// Generated 24 Jul, 2024 12:05:34 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Class generated by hbm2java
 */
@Entity
@Table(name = "class", catalog = "myschool")
public class Class implements java.io.Serializable {

	private int classId;
	private Classroom classroom;
	private Subject subject;
	private Teacher teacher;
	private String className;
	private String section;
	private Date createdAt;
	private Date updatedAt;
	private Set classStudents = new HashSet(0);

	public Class() {
	}

	public Class(int classId) {
		this.classId = classId;
	}

	public Class(int classId, Classroom classroom, Subject subject, Teacher teacher, String className, String section,
			Date createdAt, Date updatedAt, Set classStudents) {
		this.classId = classId;
		this.classroom = classroom;
		this.subject = subject;
		this.teacher = teacher;
		this.className = className;
		this.section = section;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.classStudents = classStudents;
	}

	@Id

	@Column(name = "class_id", unique = true, nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classroom_id")
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id")
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "class_name", length = 50)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "section", length = 2)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "class")
	public Set getClassStudents() {
		return this.classStudents;
	}

	public void setClassStudents(Set classStudents) {
		this.classStudents = classStudents;
	}

}
