package echoes.codejava.model;
// Generated 24 Jul, 2024 12:05:34 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name = "parent", catalog = "myschool")
public class Parent implements java.io.Serializable {

	private int parentId;
	private String parentCode;
	private String parentFullName;
	private String email;
	private String phone;
	private Date createdAt;
	private Date updatedAt;
	private Set studentParents = new HashSet(0);

	public Parent() {
	}

	public Parent(int parentId) {
		this.parentId = parentId;
	}

	public Parent(int parentId, String parentCode, String parentFullName, String email, String phone, Date createdAt,
			Date updatedAt, Set studentParents) {
		this.parentId = parentId;
		this.parentCode = parentCode;
		this.parentFullName = parentFullName;
		this.email = email;
		this.phone = phone;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.studentParents = studentParents;
	}

	@Id

	@Column(name = "parent_id", unique = true, nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_code", length = 12)
	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	@Column(name = "parent_full_name", length = 50)
	public String getParentFullName() {
		return this.parentFullName;
	}

	public void setParentFullName(String parentFullName) {
		this.parentFullName = parentFullName;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	public Set getStudentParents() {
		return this.studentParents;
	}

	public void setStudentParents(Set studentParents) {
		this.studentParents = studentParents;
	}

}

