package echoes.codejava.model;
// Generated 24 Jul, 2024 12:05:34 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentParent generated by hbm2java
 */
@Entity
@Table(name = "student_parent", catalog = "myschool")
public class StudentParent implements java.io.Serializable {

	private int studentParentId;
	private Parent parent;
	private Student student;
	private Integer relationship;

	public StudentParent() {
	}

	public StudentParent(int studentParentId) {
		this.studentParentId = studentParentId;
	}

	public StudentParent(int studentParentId, Parent parent, Student student, Integer relationship) {
		this.studentParentId = studentParentId;
		this.parent = parent;
		this.student = student;
		this.relationship = relationship;
	}

	@Id

	@Column(name = "student_parent_id", unique = true, nullable = false)
	public int getStudentParentId() {
		return this.studentParentId;
	}

	public void setStudentParentId(int studentParentId) {
		this.studentParentId = studentParentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "relationship")
	public Integer getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Integer relationship) {
		this.relationship = relationship;
	}

}
