package echoes.codejava.model;
// Generated 24 Jul, 2024 12:05:34 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "myschool")
public class Subject implements java.io.Serializable {

	private Integer subjectId;
	private School school;
	private String title;
	private Integer stage;
	private Integer term;
	private Integer carryMark;
	private Date createdAt;
	private Date updatedAt;
	private Set classes = new HashSet(0);

	public Subject() {
	}

	public Subject(School school, String title, Integer stage, Integer term, Integer carryMark, Date createdAt,
			Date updatedAt, Set classes) {
		this.school = school;
		this.title = title;
		this.stage = stage;
		this.term = term;
		this.carryMark = carryMark;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.classes = classes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "subject_id", unique = true, nullable = false)
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "stage")
	public Integer getStage() {
		return this.stage;
	}

	public void setStage(Integer stage) {
		this.stage = stage;
	}

	@Column(name = "term")
	public Integer getTerm() {
		return this.term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	@Column(name = "carry_mark")
	public Integer getCarryMark() {
		return this.carryMark;
	}

	public void setCarryMark(Integer carryMark) {
		this.carryMark = carryMark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
