package echoes.codejava.model;
// Generated 24 Jul, 2024 12:05:34 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "myschool")
public class Teacher implements java.io.Serializable {

	private int teacherId;
	private String teacherCode;
	private String teacherFullName;
	private Short gender;
	private Date dob;
	private String email;
	private String phone;
	private Short isActive;
	private Date joinDate;
	private Short workingDays;
	private Date createdAt;
	private Date updatedAt;
	private Set classes = new HashSet(0);

	public Teacher() {
	}

	public Teacher(int teacherId) {
		this.teacherId = teacherId;
	}

	public Teacher(int teacherId, String teacherCode, String teacherFullName, Short gender, Date dob, String email,
			String phone, Short isActive, Date joinDate, Short workingDays, Date createdAt, Date updatedAt,
			Set classes) {
		this.teacherId = teacherId;
		this.teacherCode = teacherCode;
		this.teacherFullName = teacherFullName;
		this.gender = gender;
		this.dob = dob;
		this.email = email;
		this.phone = phone;
		this.isActive = isActive;
		this.joinDate = joinDate;
		this.workingDays = workingDays;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.classes = classes;
	}

	@Id

	@Column(name = "teacher_id", unique = true, nullable = false)
	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "teacher_code", length = 12)
	public String getTeacherCode() {
		return this.teacherCode;
	}

	public void setTeacherCode(String teacherCode) {
		this.teacherCode = teacherCode;
	}

	@Column(name = "teacher_full_name", length = 75)
	public String getTeacherFullName() {
		return this.teacherFullName;
	}

	public void setTeacherFullName(String teacherFullName) {
		this.teacherFullName = teacherFullName;
	}

	@Column(name = "gender")
	public Short getGender() {
		return this.gender;
	}

	public void setGender(Short gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "email", length = 75)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "is_active")
	public Short getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Short isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "join_date", length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "working_days")
	public Short getWorkingDays() {
		return this.workingDays;
	}

	public void setWorkingDays(Short workingDays) {
		this.workingDays = workingDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
