package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Classroom generated by hbm2java
 */
public class Classroom implements java.io.Serializable {

	private int classroomId;
	private Integer capacity;
	private Integer roomType;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private Set classes = new HashSet(0);

	public Classroom() {
	}

	public Classroom(int classroomId) {
		this.classroomId = classroomId;
	}

	public Classroom(int classroomId, Integer capacity, Integer roomType, String description, Date createdAt,
			Date updatedAt, Set classes) {
		this.classroomId = classroomId;
		this.capacity = capacity;
		this.roomType = roomType;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.classes = classes;
	}

	public int getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(int classroomId) {
		this.classroomId = classroomId;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getRoomType() {
		return this.roomType;
	}

	public void setRoomType(Integer roomType) {
		this.roomType = roomType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
