package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * ClassStudent generated by hbm2java
 */
public class ClassStudent implements java.io.Serializable {

	private long classStudentId;
	private Class class_;
	private Student student;

	public ClassStudent() {
	}

	public ClassStudent(long classStudentId) {
		this.classStudentId = classStudentId;
	}

	public ClassStudent(long classStudentId, Class class_, Student student) {
		this.classStudentId = classStudentId;
		this.class_ = class_;
		this.student = student;
	}

	public long getClassStudentId() {
		return this.classStudentId;
	}

	public void setClassStudentId(long classStudentId) {
		this.classStudentId = classStudentId;
	}

	public Class getClass() {
		return this.class_;
	}

	public void setClass(Class class_) {
		this.class_ = class_;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
