package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * CurrentDeptEmp generated by hbm2java
 */
public class CurrentDeptEmp implements java.io.Serializable {

	private CurrentDeptEmpId id;

	public CurrentDeptEmp() {
	}

	public CurrentDeptEmp(CurrentDeptEmpId id) {
		this.id = id;
	}

	public CurrentDeptEmpId getId() {
		return this.id;
	}

	public void setId(CurrentDeptEmpId id) {
		this.id = id;
	}

}
