package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private String customerCode;
	private String custmerName;
	private String customerType;

	public Customers() {
	}

	public Customers(String customerCode) {
		this.customerCode = customerCode;
	}

	public Customers(String customerCode, String custmerName, String customerType) {
		this.customerCode = customerCode;
		this.custmerName = custmerName;
		this.customerType = customerType;
	}

	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getCustmerName() {
		return this.custmerName;
	}

	public void setCustmerName(String custmerName) {
		this.custmerName = custmerName;
	}

	public String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

}
