package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * DeptEmpLatestDate generated by hbm2java
 */
public class DeptEmpLatestDate implements java.io.Serializable {

	private DeptEmpLatestDateId id;

	public DeptEmpLatestDate() {
	}

	public DeptEmpLatestDate(DeptEmpLatestDateId id) {
		this.id = id;
	}

	public DeptEmpLatestDateId getId() {
		return this.id;
	}

	public void setId(DeptEmpLatestDateId id) {
		this.id = id;
	}

}
