package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * HostSummaryByStatementLatency generated by hbm2java
 */
public class HostSummaryByStatementLatency implements java.io.Serializable {

	private HostSummaryByStatementLatencyId id;

	public HostSummaryByStatementLatency() {
	}

	public HostSummaryByStatementLatency(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public HostSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
