package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * HostSummary generated by hbm2java
 */
public class HostSummary implements java.io.Serializable {

	private HostSummaryId id;

	public HostSummary() {
	}

	public HostSummary(HostSummaryId id) {
		this.id = id;
	}

	public HostSummaryId getId() {
		return this.id;
	}

	public void setId(HostSummaryId id) {
		this.id = id;
	}

}
