package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * HostSummaryByFileIoType generated by hbm2java
 */
public class HostSummaryByFileIoType implements java.io.Serializable {

	private HostSummaryByFileIoTypeId id;

	public HostSummaryByFileIoType() {
	}

	public HostSummaryByFileIoType(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public HostSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
