package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * HostSummaryByStages generated by hbm2java
 */
public class HostSummaryByStages implements java.io.Serializable {

	private HostSummaryByStagesId id;

	public HostSummaryByStages() {
	}

	public HostSummaryByStages(HostSummaryByStagesId id) {
		this.id = id;
	}

	public HostSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStagesId id) {
		this.id = id;
	}

}
