package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * InnodbBufferStatsBySchema generated by hbm2java
 */
public class InnodbBufferStatsBySchema implements java.io.Serializable {

	private InnodbBufferStatsBySchemaId id;

	public InnodbBufferStatsBySchema() {
	}

	public InnodbBufferStatsBySchema(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

	public InnodbBufferStatsBySchemaId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

}
