package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * InnodbBufferStatsByTable generated by hbm2java
 */
public class InnodbBufferStatsByTable implements java.io.Serializable {

	private InnodbBufferStatsByTableId id;

	public InnodbBufferStatsByTable() {
	}

	public InnodbBufferStatsByTable(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

	public InnodbBufferStatsByTableId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

}
