package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * IoGlobalByFileByBytes generated by hbm2java
 */
public class IoGlobalByFileByBytes implements java.io.Serializable {

	private IoGlobalByFileByBytesId id;

	public IoGlobalByFileByBytes() {
	}

	public IoGlobalByFileByBytes(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

	public IoGlobalByFileByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

}
