package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * IoGlobalByFileByLatency generated by hbm2java
 */
public class IoGlobalByFileByLatency implements java.io.Serializable {

	private IoGlobalByFileByLatencyId id;

	public IoGlobalByFileByLatency() {
	}

	public IoGlobalByFileByLatency(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByFileByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

}
