package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * IoGlobalByWaitByBytes generated by hbm2java
 */
public class IoGlobalByWaitByBytes implements java.io.Serializable {

	private IoGlobalByWaitByBytesId id;

	public IoGlobalByWaitByBytes() {
	}

	public IoGlobalByWaitByBytes(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

	public IoGlobalByWaitByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

}
