package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * LatestFileIo generated by hbm2java
 */
public class LatestFileIo implements java.io.Serializable {

	private LatestFileIoId id;

	public LatestFileIo() {
	}

	public LatestFileIo(LatestFileIoId id) {
		this.id = id;
	}

	public LatestFileIoId getId() {
		return this.id;
	}

	public void setId(LatestFileIoId id) {
		this.id = id;
	}

}
