package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * Markets generated by hbm2java
 */
public class Markets implements java.io.Serializable {

	private String marketsCode;
	private String marketsName;
	private String zone;

	public Markets() {
	}

	public Markets(String marketsCode) {
		this.marketsCode = marketsCode;
	}

	public Markets(String marketsCode, String marketsName, String zone) {
		this.marketsCode = marketsCode;
		this.marketsName = marketsName;
		this.zone = zone;
	}

	public String getMarketsCode() {
		return this.marketsCode;
	}

	public void setMarketsCode(String marketsCode) {
		this.marketsCode = marketsCode;
	}

	public String getMarketsName() {
		return this.marketsName;
	}

	public void setMarketsName(String marketsName) {
		this.marketsName = marketsName;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

}
