package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * MemoryByHostByCurrentBytes generated by hbm2java
 */
public class MemoryByHostByCurrentBytes implements java.io.Serializable {

	private MemoryByHostByCurrentBytesId id;

	public MemoryByHostByCurrentBytes() {
	}

	public MemoryByHostByCurrentBytes(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByHostByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

}
