package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
