package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * MemoryGlobalByCurrentBytes generated by hbm2java
 */
public class MemoryGlobalByCurrentBytes implements java.io.Serializable {

	private MemoryGlobalByCurrentBytesId id;

	public MemoryGlobalByCurrentBytes() {
	}

	public MemoryGlobalByCurrentBytes(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryGlobalByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

}
