package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * MemoryByUserByCurrentBytes generated by hbm2java
 */
public class MemoryByUserByCurrentBytes implements java.io.Serializable {

	private MemoryByUserByCurrentBytesId id;

	public MemoryByUserByCurrentBytes() {
	}

	public MemoryByUserByCurrentBytes(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByUserByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

}
