package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parent generated by hbm2java
 */
public class Parent implements java.io.Serializable {

	private int parentId;
	private String parentCode;
	private String parentFullName;
	private String email;
	private String phone;
	private Date createdAt;
	private Date updatedAt;
	private Set studentParents = new HashSet(0);

	public Parent() {
	}

	public Parent(int parentId) {
		this.parentId = parentId;
	}

	public Parent(int parentId, String parentCode, String parentFullName, String email, String phone, Date createdAt,
			Date updatedAt, Set studentParents) {
		this.parentId = parentId;
		this.parentCode = parentCode;
		this.parentFullName = parentFullName;
		this.email = email;
		this.phone = phone;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.studentParents = studentParents;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getParentFullName() {
		return this.parentFullName;
	}

	public void setParentFullName(String parentFullName) {
		this.parentFullName = parentFullName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getStudentParents() {
		return this.studentParents;
	}

	public void setStudentParents(Set studentParents) {
		this.studentParents = studentParents;
	}

}
