package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * Processlist generated by hbm2java
 */
public class Processlist implements java.io.Serializable {

	private ProcesslistId id;

	public Processlist() {
	}

	public Processlist(ProcesslistId id) {
		this.id = id;
	}

	public ProcesslistId getId() {
		return this.id;
	}

	public void setId(ProcesslistId id) {
		this.id = id;
	}

}
