package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * PsCheckLostInstrumentation generated by hbm2java
 */
public class PsCheckLostInstrumentation implements java.io.Serializable {

	private PsCheckLostInstrumentationId id;

	public PsCheckLostInstrumentation() {
	}

	public PsCheckLostInstrumentation(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

	public PsCheckLostInstrumentationId getId() {
		return this.id;
	}

	public void setId(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

}
