package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * SchemaTableStatistics generated by hbm2java
 */
public class SchemaTableStatistics implements java.io.Serializable {

	private SchemaTableStatisticsId id;

	public SchemaTableStatistics() {
	}

	public SchemaTableStatistics(SchemaTableStatisticsId id) {
		this.id = id;
	}

	public SchemaTableStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsId id) {
		this.id = id;
	}

}
