package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * SchemaTableLockWaits generated by hbm2java
 */
public class SchemaTableLockWaits implements java.io.Serializable {

	private SchemaTableLockWaitsId id;

	public SchemaTableLockWaits() {
	}

	public SchemaTableLockWaits(SchemaTableLockWaitsId id) {
		this.id = id;
	}

	public SchemaTableLockWaitsId getId() {
		return this.id;
	}

	public void setId(SchemaTableLockWaitsId id) {
		this.id = id;
	}

}
