package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * SchemaAutoIncrementColumns generated by hbm2java
 */
public class SchemaAutoIncrementColumns implements java.io.Serializable {

	private SchemaAutoIncrementColumnsId id;

	public SchemaAutoIncrementColumns() {
	}

	public SchemaAutoIncrementColumns(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

	public SchemaAutoIncrementColumnsId getId() {
		return this.id;
	}

	public void setId(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

}
