package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * SchemaUnusedIndexes generated by hbm2java
 */
public class SchemaUnusedIndexes implements java.io.Serializable {

	private SchemaUnusedIndexesId id;

	public SchemaUnusedIndexes() {
	}

	public SchemaUnusedIndexes(SchemaUnusedIndexesId id) {
		this.id = id;
	}

	public SchemaUnusedIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaUnusedIndexesId id) {
		this.id = id;
	}

}
