package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

	private Integer schoolId;
	private String schoolTitle;
	private Byte levelCount;
	private Boolean isActive;
	private Date createdAt;
	private Date updatedAt;
	private Set subjects = new HashSet(0);
	private Set students = new HashSet(0);

	public School() {
	}

	public School(String schoolTitle, Byte levelCount, Boolean isActive, Date createdAt, Date updatedAt, Set subjects,
			Set students) {
		this.schoolTitle = schoolTitle;
		this.levelCount = levelCount;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.subjects = subjects;
		this.students = students;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getSchoolTitle() {
		return this.schoolTitle;
	}

	public void setSchoolTitle(String schoolTitle) {
		this.schoolTitle = schoolTitle;
	}

	public Byte getLevelCount() {
		return this.levelCount;
	}

	public void setLevelCount(Byte levelCount) {
		this.levelCount = levelCount;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set subjects) {
		this.subjects = subjects;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
