package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StatementAnalysis generated by hbm2java
 */
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
