package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StatementsWithSorting generated by hbm2java
 */
public class StatementsWithSorting implements java.io.Serializable {

	private StatementsWithSortingId id;

	public StatementsWithSorting() {
	}

	public StatementsWithSorting(StatementsWithSortingId id) {
		this.id = id;
	}

	public StatementsWithSortingId getId() {
		return this.id;
	}

	public void setId(StatementsWithSortingId id) {
		this.id = id;
	}

}
