package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StatementsWithErrorsOrWarnings generated by hbm2java
 */
public class StatementsWithErrorsOrWarnings implements java.io.Serializable {

	private StatementsWithErrorsOrWarningsId id;

	public StatementsWithErrorsOrWarnings() {
	}

	public StatementsWithErrorsOrWarnings(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

	public StatementsWithErrorsOrWarningsId getId() {
		return this.id;
	}

	public void setId(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

}
