package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StatementsWithTempTables generated by hbm2java
 */
public class StatementsWithTempTables implements java.io.Serializable {

	private StatementsWithTempTablesId id;

	public StatementsWithTempTables() {
	}

	public StatementsWithTempTables(StatementsWithTempTablesId id) {
		this.id = id;
	}

	public StatementsWithTempTablesId getId() {
		return this.id;
	}

	public void setId(StatementsWithTempTablesId id) {
		this.id = id;
	}

}
