package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StatementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class StatementsWithRuntimesIn95thPercentile implements java.io.Serializable {

	private StatementsWithRuntimesIn95thPercentileId id;

	public StatementsWithRuntimesIn95thPercentile() {
	}

	public StatementsWithRuntimesIn95thPercentile(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

	public StatementsWithRuntimesIn95thPercentileId getId() {
		return this.id;
	}

	public void setId(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

}
