package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * StudentParent generated by hbm2java
 */
public class StudentParent implements java.io.Serializable {

	private int studentParentId;
	private Parent parent;
	private Student student;
	private Integer relationship;

	public StudentParent() {
	}

	public StudentParent(int studentParentId) {
		this.studentParentId = studentParentId;
	}

	public StudentParent(int studentParentId, Parent parent, Student student, Integer relationship) {
		this.studentParentId = studentParentId;
		this.parent = parent;
		this.student = student;
		this.relationship = relationship;
	}

	public int getStudentParentId() {
		return this.studentParentId;
	}

	public void setStudentParentId(int studentParentId) {
		this.studentParentId = studentParentId;
	}

	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Integer getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Integer relationship) {
		this.relationship = relationship;
	}

}
