package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer studentId;
	private School school;
	private String studentCode;
	private String studentFullName;
	private Short gender;
	private Date dob;
	private String email;
	private String phone;
	private Integer stage;
	private String section;
	private Short isActive;
	private Date joinDate;
	private Date createdAt;
	private Date updatedAt;
	private Set studentParents = new HashSet(0);
	private Set classStudents = new HashSet(0);

	public Student() {
	}

	public Student(School school, String studentCode, String studentFullName, Short gender, Date dob, String email,
			String phone, Integer stage, String section, Short isActive, Date joinDate, Date createdAt, Date updatedAt,
			Set studentParents, Set classStudents) {
		this.school = school;
		this.studentCode = studentCode;
		this.studentFullName = studentFullName;
		this.gender = gender;
		this.dob = dob;
		this.email = email;
		this.phone = phone;
		this.stage = stage;
		this.section = section;
		this.isActive = isActive;
		this.joinDate = joinDate;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.studentParents = studentParents;
		this.classStudents = classStudents;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	public String getStudentCode() {
		return this.studentCode;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public String getStudentFullName() {
		return this.studentFullName;
	}

	public void setStudentFullName(String studentFullName) {
		this.studentFullName = studentFullName;
	}

	public Short getGender() {
		return this.gender;
	}

	public void setGender(Short gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getStage() {
		return this.stage;
	}

	public void setStage(Integer stage) {
		this.stage = stage;
	}

	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public Short getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Short isActive) {
		this.isActive = isActive;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getStudentParents() {
		return this.studentParents;
	}

	public void setStudentParents(Set studentParents) {
		this.studentParents = studentParents;
	}

	public Set getClassStudents() {
		return this.classStudents;
	}

	public void setClassStudents(Set classStudents) {
		this.classStudents = classStudents;
	}

}
