package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;

/**
 * TransactionsId generated by hbm2java
 */
public class TransactionsId implements java.io.Serializable {

	private String productCode;
	private String customerCode;
	private String marketCode;
	private Date orderDate;
	private Integer salesQty;
	private Double salesAmount;
	private String currency;

	public TransactionsId() {
	}

	public TransactionsId(String productCode, String customerCode, String marketCode, Date orderDate, Integer salesQty,
			Double salesAmount, String currency) {
		this.productCode = productCode;
		this.customerCode = customerCode;
		this.marketCode = marketCode;
		this.orderDate = orderDate;
		this.salesQty = salesQty;
		this.salesAmount = salesAmount;
		this.currency = currency;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getMarketCode() {
		return this.marketCode;
	}

	public void setMarketCode(String marketCode) {
		this.marketCode = marketCode;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Integer getSalesQty() {
		return this.salesQty;
	}

	public void setSalesQty(Integer salesQty) {
		this.salesQty = salesQty;
	}

	public Double getSalesAmount() {
		return this.salesAmount;
	}

	public void setSalesAmount(Double salesAmount) {
		this.salesAmount = salesAmount;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionsId))
			return false;
		TransactionsId castOther = (TransactionsId) other;

		return ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null
				&& castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
				&& ((this.getCustomerCode() == castOther.getCustomerCode())
						|| (this.getCustomerCode() != null && castOther.getCustomerCode() != null
								&& this.getCustomerCode().equals(castOther.getCustomerCode())))
				&& ((this.getMarketCode() == castOther.getMarketCode()) || (this.getMarketCode() != null
						&& castOther.getMarketCode() != null && this.getMarketCode().equals(castOther.getMarketCode())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this.getOrderDate() != null
						&& castOther.getOrderDate() != null && this.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getSalesQty() == castOther.getSalesQty()) || (this.getSalesQty() != null
						&& castOther.getSalesQty() != null && this.getSalesQty().equals(castOther.getSalesQty())))
				&& ((this.getSalesAmount() == castOther.getSalesAmount())
						|| (this.getSalesAmount() != null && castOther.getSalesAmount() != null
								&& this.getSalesAmount().equals(castOther.getSalesAmount())))
				&& ((this.getCurrency() == castOther.getCurrency()) || (this.getCurrency() != null
						&& castOther.getCurrency() != null && this.getCurrency().equals(castOther.getCurrency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
		result = 37 * result + (getCustomerCode() == null ? 0 : this.getCustomerCode().hashCode());
		result = 37 * result + (getMarketCode() == null ? 0 : this.getMarketCode().hashCode());
		result = 37 * result + (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result + (getSalesQty() == null ? 0 : this.getSalesQty().hashCode());
		result = 37 * result + (getSalesAmount() == null ? 0 : this.getSalesAmount().hashCode());
		result = 37 * result + (getCurrency() == null ? 0 : this.getCurrency().hashCode());
		return result;
	}

}
