package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private TransactionsId id;

	public Transactions() {
	}

	public Transactions(TransactionsId id) {
		this.id = id;
	}

	public TransactionsId getId() {
		return this.id;
	}

	public void setId(TransactionsId id) {
		this.id = id;
	}

}
