package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * UserSummaryByStages generated by hbm2java
 */
public class UserSummaryByStages implements java.io.Serializable {

	private UserSummaryByStagesId id;

	public UserSummaryByStages() {
	}

	public UserSummaryByStages(UserSummaryByStagesId id) {
		this.id = id;
	}

	public UserSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStagesId id) {
		this.id = id;
	}

}
