package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * UserSummaryByFileIoType generated by hbm2java
 */
public class UserSummaryByFileIoType implements java.io.Serializable {

	private UserSummaryByFileIoTypeId id;

	public UserSummaryByFileIoType() {
	}

	public UserSummaryByFileIoType(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public UserSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
