package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * UserSummaryByFileIo generated by hbm2java
 */
public class UserSummaryByFileIo implements java.io.Serializable {

	private UserSummaryByFileIoId id;

	public UserSummaryByFileIo() {
	}

	public UserSummaryByFileIo(UserSummaryByFileIoId id) {
		this.id = id;
	}

	public UserSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoId id) {
		this.id = id;
	}

}
