package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * UserSummaryByStatementLatency generated by hbm2java
 */
public class UserSummaryByStatementLatency implements java.io.Serializable {

	private UserSummaryByStatementLatencyId id;

	public UserSummaryByStatementLatency() {
	}

	public UserSummaryByStatementLatency(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public UserSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
