package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * WaitClassesGlobalByLatency generated by hbm2java
 */
public class WaitClassesGlobalByLatency implements java.io.Serializable {

	private WaitClassesGlobalByLatencyId id;

	public WaitClassesGlobalByLatency() {
	}

	public WaitClassesGlobalByLatency(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

}
