package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final

/**
 * WaitClassesGlobalByAvgLatency generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatency implements java.io.Serializable {

	private WaitClassesGlobalByAvgLatencyId id;

	public WaitClassesGlobalByAvgLatency() {
	}

	public WaitClassesGlobalByAvgLatency(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByAvgLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

}
