package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;

/**
 * X.hostSummaryByStatementLatencyId generated by hbm2java
 */
public class X.hostSummaryByStatementLatencyId  implements java.io.Serializable {


     private String host;
     private BigDecimal total;
     private BigDecimal totalLatency;
     private Long maxLatency;
     private BigDecimal lockLatency;
     private BigDecimal cpuLatency;
     private BigDecimal rowsSent;
     private BigDecimal rowsExamined;
     private BigDecimal rowsAffected;
     private BigDecimal fullScans;

    public X.hostSummaryByStatementLatencyId() {
    }

    public X.hostSummaryByStatementLatencyId(String host, BigDecimal total, BigDecimal totalLatency, Long maxLatency, BigDecimal lockLatency, BigDecimal cpuLatency, BigDecimal rowsSent, BigDecimal rowsExamined, BigDecimal rowsAffected, BigDecimal fullScans) {
       this.host = host;
       this.total = total;
       this.totalLatency = totalLatency;
       this.maxLatency = maxLatency;
       this.lockLatency = lockLatency;
       this.cpuLatency = cpuLatency;
       this.rowsSent = rowsSent;
       this.rowsExamined = rowsExamined;
       this.rowsAffected = rowsAffected;
       this.fullScans = fullScans;
    }
   
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public BigDecimal getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(BigDecimal totalLatency) {
        this.totalLatency = totalLatency;
    }
    public Long getMaxLatency() {
        return this.maxLatency;
    }
    
    public void setMaxLatency(Long maxLatency) {
        this.maxLatency = maxLatency;
    }
    public BigDecimal getLockLatency() {
        return this.lockLatency;
    }
    
    public void setLockLatency(BigDecimal lockLatency) {
        this.lockLatency = lockLatency;
    }
    public BigDecimal getCpuLatency() {
        return this.cpuLatency;
    }
    
    public void setCpuLatency(BigDecimal cpuLatency) {
        this.cpuLatency = cpuLatency;
    }
    public BigDecimal getRowsSent() {
        return this.rowsSent;
    }
    
    public void setRowsSent(BigDecimal rowsSent) {
        this.rowsSent = rowsSent;
    }
    public BigDecimal getRowsExamined() {
        return this.rowsExamined;
    }
    
    public void setRowsExamined(BigDecimal rowsExamined) {
        this.rowsExamined = rowsExamined;
    }
    public BigDecimal getRowsAffected() {
        return this.rowsAffected;
    }
    
    public void setRowsAffected(BigDecimal rowsAffected) {
        this.rowsAffected = rowsAffected;
    }
    public BigDecimal getFullScans() {
        return this.fullScans;
    }
    
    public void setFullScans(BigDecimal fullScans) {
        this.fullScans = fullScans;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.hostSummaryByStatementLatencyId) ) return false;
		 X.hostSummaryByStatementLatencyId castOther = ( X.hostSummaryByStatementLatencyId ) other; 
         
		 return ( (this.getHost()==castOther.getHost()) || ( this.getHost()!=null && castOther.getHost()!=null && this.getHost().equals(castOther.getHost()) ) )
 && ( (this.getTotal()==castOther.getTotal()) || ( this.getTotal()!=null && castOther.getTotal()!=null && this.getTotal().equals(castOther.getTotal()) ) )
 && ( (this.getTotalLatency()==castOther.getTotalLatency()) || ( this.getTotalLatency()!=null && castOther.getTotalLatency()!=null && this.getTotalLatency().equals(castOther.getTotalLatency()) ) )
 && ( (this.getMaxLatency()==castOther.getMaxLatency()) || ( this.getMaxLatency()!=null && castOther.getMaxLatency()!=null && this.getMaxLatency().equals(castOther.getMaxLatency()) ) )
 && ( (this.getLockLatency()==castOther.getLockLatency()) || ( this.getLockLatency()!=null && castOther.getLockLatency()!=null && this.getLockLatency().equals(castOther.getLockLatency()) ) )
 && ( (this.getCpuLatency()==castOther.getCpuLatency()) || ( this.getCpuLatency()!=null && castOther.getCpuLatency()!=null && this.getCpuLatency().equals(castOther.getCpuLatency()) ) )
 && ( (this.getRowsSent()==castOther.getRowsSent()) || ( this.getRowsSent()!=null && castOther.getRowsSent()!=null && this.getRowsSent().equals(castOther.getRowsSent()) ) )
 && ( (this.getRowsExamined()==castOther.getRowsExamined()) || ( this.getRowsExamined()!=null && castOther.getRowsExamined()!=null && this.getRowsExamined().equals(castOther.getRowsExamined()) ) )
 && ( (this.getRowsAffected()==castOther.getRowsAffected()) || ( this.getRowsAffected()!=null && castOther.getRowsAffected()!=null && this.getRowsAffected().equals(castOther.getRowsAffected()) ) )
 && ( (this.getFullScans()==castOther.getFullScans()) || ( this.getFullScans()!=null && castOther.getFullScans()!=null && this.getFullScans().equals(castOther.getFullScans()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHost() == null ? 0 : this.getHost().hashCode() );
         result = 37 * result + ( getTotal() == null ? 0 : this.getTotal().hashCode() );
         result = 37 * result + ( getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode() );
         result = 37 * result + ( getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode() );
         result = 37 * result + ( getLockLatency() == null ? 0 : this.getLockLatency().hashCode() );
         result = 37 * result + ( getCpuLatency() == null ? 0 : this.getCpuLatency().hashCode() );
         result = 37 * result + ( getRowsSent() == null ? 0 : this.getRowsSent().hashCode() );
         result = 37 * result + ( getRowsExamined() == null ? 0 : this.getRowsExamined().hashCode() );
         result = 37 * result + ( getRowsAffected() == null ? 0 : this.getRowsAffected().hashCode() );
         result = 37 * result + ( getFullScans() == null ? 0 : this.getFullScans().hashCode() );
         return result;
   }   


}


