package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.hostSummaryByFileIoTypeId;

/**
 * X.hostSummaryByFileIoType generated by hbm2java
 */
public class X.hostSummaryByFileIoType  implements java.io.Serializable {


     private X.hostSummaryByFileIoTypeId id;

    public X.hostSummaryByFileIoType() {
    }

    public X.hostSummaryByFileIoType(X.hostSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


