package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.hostSummaryByStagesId;

/**
 * X.hostSummaryByStages generated by hbm2java
 */
public class X.hostSummaryByStages  implements java.io.Serializable {


     private X.hostSummaryByStagesId id;

    public X.hostSummaryByStages() {
    }

    public X.hostSummaryByStages(X.hostSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStagesId id) {
        this.id = id;
    }




}


