package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.hostSummaryByStatementLatencyId;

/**
 * X.hostSummaryByStatementLatency generated by hbm2java
 */
public class X.hostSummaryByStatementLatency  implements java.io.Serializable {


     private X.hostSummaryByStatementLatencyId id;

    public X.hostSummaryByStatementLatency() {
    }

    public X.hostSummaryByStatementLatency(X.hostSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


