package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.hostSummaryId;

/**
 * X.hostSummary generated by hbm2java
 */
public class X.hostSummary  implements java.io.Serializable {


     private X.hostSummaryId id;

    public X.hostSummary() {
    }

    public X.hostSummary(X.hostSummaryId id) {
       this.id = id;
    }
   
    public X.hostSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryId id) {
        this.id = id;
    }




}


