package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.innodbBufferStatsByTableId;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


