package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.ioGlobalByWaitByLatencyId;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


