package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.ioGlobalByFileByBytesId;

/**
 * X.ioGlobalByFileByBytes generated by hbm2java
 */
public class X.ioGlobalByFileByBytes  implements java.io.Serializable {


     private X.ioGlobalByFileByBytesId id;

    public X.ioGlobalByFileByBytes() {
    }

    public X.ioGlobalByFileByBytes(X.ioGlobalByFileByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByBytesId id) {
        this.id = id;
    }




}


