package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.ioGlobalByFileByLatencyId;

/**
 * X.ioGlobalByFileByLatency generated by hbm2java
 */
public class X.ioGlobalByFileByLatency  implements java.io.Serializable {


     private X.ioGlobalByFileByLatencyId id;

    public X.ioGlobalByFileByLatency() {
    }

    public X.ioGlobalByFileByLatency(X.ioGlobalByFileByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByLatencyId id) {
        this.id = id;
    }




}


