package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.ioGlobalByWaitByBytesId;

/**
 * X.ioGlobalByWaitByBytes generated by hbm2java
 */
public class X.ioGlobalByWaitByBytes  implements java.io.Serializable {


     private X.ioGlobalByWaitByBytesId id;

    public X.ioGlobalByWaitByBytes() {
    }

    public X.ioGlobalByWaitByBytes(X.ioGlobalByWaitByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByBytesId id) {
        this.id = id;
    }




}


