package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.memoryByThreadByCurrentBytesId;

/**
 * X.memoryByThreadByCurrentBytes generated by hbm2java
 */
public class X.memoryByThreadByCurrentBytes  implements java.io.Serializable {


     private X.memoryByThreadByCurrentBytesId id;

    public X.memoryByThreadByCurrentBytes() {
    }

    public X.memoryByThreadByCurrentBytes(X.memoryByThreadByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByThreadByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByThreadByCurrentBytesId id) {
        this.id = id;
    }




}


