package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.memoryByHostByCurrentBytesId;

/**
 * X.memoryByHostByCurrentBytes generated by hbm2java
 */
public class X.memoryByHostByCurrentBytes  implements java.io.Serializable {


     private X.memoryByHostByCurrentBytesId id;

    public X.memoryByHostByCurrentBytes() {
    }

    public X.memoryByHostByCurrentBytes(X.memoryByHostByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByHostByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByHostByCurrentBytesId id) {
        this.id = id;
    }




}


