package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.memoryGlobalByCurrentBytesId;

/**
 * X.memoryGlobalByCurrentBytes generated by hbm2java
 */
public class X.memoryGlobalByCurrentBytes  implements java.io.Serializable {


     private X.memoryGlobalByCurrentBytesId id;

    public X.memoryGlobalByCurrentBytes() {
    }

    public X.memoryGlobalByCurrentBytes(X.memoryGlobalByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryGlobalByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryGlobalByCurrentBytesId id) {
        this.id = id;
    }




}


