package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.memoryByUserByCurrentBytesId;

/**
 * X.memoryByUserByCurrentBytes generated by hbm2java
 */
public class X.memoryByUserByCurrentBytes  implements java.io.Serializable {


     private X.memoryByUserByCurrentBytesId id;

    public X.memoryByUserByCurrentBytes() {
    }

    public X.memoryByUserByCurrentBytes(X.memoryByUserByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByUserByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByUserByCurrentBytesId id) {
        this.id = id;
    }




}


