package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;

/**
 * X.memoryGlobalTotal generated by hbm2java
 */
public class X.memoryGlobalTotal  implements java.io.Serializable {


     private BigDecimal totalAllocated;

    public X.memoryGlobalTotal() {
    }

    public X.memoryGlobalTotal(BigDecimal totalAllocated) {
       this.totalAllocated = totalAllocated;
    }
   
    public BigDecimal getTotalAllocated() {
        return this.totalAllocated;
    }
    
    public void setTotalAllocated(BigDecimal totalAllocated) {
        this.totalAllocated = totalAllocated;
    }




}


