package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.processlistId;

/**
 * X.processlist generated by hbm2java
 */
public class X.processlist  implements java.io.Serializable {


     private X.processlistId id;

    public X.processlist() {
    }

    public X.processlist(X.processlistId id) {
       this.id = id;
    }
   
    public X.processlistId getId() {
        return this.id;
    }
    
    public void setId(X.processlistId id) {
        this.id = id;
    }




}


