package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.psSchemaTableStatisticsIoId;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


