package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.psDigestAvgLatencyDistributionId;

/**
 * X.psDigestAvgLatencyDistribution generated by hbm2java
 */
public class X.psDigestAvgLatencyDistribution  implements java.io.Serializable {


     private X.psDigestAvgLatencyDistributionId id;

    public X.psDigestAvgLatencyDistribution() {
    }

    public X.psDigestAvgLatencyDistribution(X.psDigestAvgLatencyDistributionId id) {
       this.id = id;
    }
   
    public X.psDigestAvgLatencyDistributionId getId() {
        return this.id;
    }
    
    public void setId(X.psDigestAvgLatencyDistributionId id) {
        this.id = id;
    }




}


