package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import java.math.BigDecimal;

/**
 * X.schemaTableStatisticsWithBufferId generated by hbm2java
 */
public class X.schemaTableStatisticsWithBufferId  implements java.io.Serializable {


     private String tableSchema;
     private String tableName;
     private long rowsFetched;
     private long fetchLatency;
     private long rowsInserted;
     private long insertLatency;
     private long rowsUpdated;
     private long updateLatency;
     private long rowsDeleted;
     private long deleteLatency;
     private BigDecimal ioReadRequests;
     private BigDecimal ioRead;
     private BigDecimal ioReadLatency;
     private BigDecimal ioWriteRequests;
     private BigDecimal ioWrite;
     private BigDecimal ioWriteLatency;
     private BigDecimal ioMiscRequests;
     private BigDecimal ioMiscLatency;
     private BigDecimal innodbBufferAllocated;
     private BigDecimal innodbBufferData;
     private BigDecimal innodbBufferFree;
     private Long innodbBufferPages;
     private Long innodbBufferPagesHashed;
     private Long innodbBufferPagesOld;
     private BigDecimal innodbBufferRowsCached;

    public X.schemaTableStatisticsWithBufferId() {
    }

	
    public X.schemaTableStatisticsWithBufferId(long rowsFetched, long fetchLatency, long rowsInserted, long insertLatency, long rowsUpdated, long updateLatency, long rowsDeleted, long deleteLatency) {
        this.rowsFetched = rowsFetched;
        this.fetchLatency = fetchLatency;
        this.rowsInserted = rowsInserted;
        this.insertLatency = insertLatency;
        this.rowsUpdated = rowsUpdated;
        this.updateLatency = updateLatency;
        this.rowsDeleted = rowsDeleted;
        this.deleteLatency = deleteLatency;
    }
    public X.schemaTableStatisticsWithBufferId(String tableSchema, String tableName, long rowsFetched, long fetchLatency, long rowsInserted, long insertLatency, long rowsUpdated, long updateLatency, long rowsDeleted, long deleteLatency, BigDecimal ioReadRequests, BigDecimal ioRead, BigDecimal ioReadLatency, BigDecimal ioWriteRequests, BigDecimal ioWrite, BigDecimal ioWriteLatency, BigDecimal ioMiscRequests, BigDecimal ioMiscLatency, BigDecimal innodbBufferAllocated, BigDecimal innodbBufferData, BigDecimal innodbBufferFree, Long innodbBufferPages, Long innodbBufferPagesHashed, Long innodbBufferPagesOld, BigDecimal innodbBufferRowsCached) {
       this.tableSchema = tableSchema;
       this.tableName = tableName;
       this.rowsFetched = rowsFetched;
       this.fetchLatency = fetchLatency;
       this.rowsInserted = rowsInserted;
       this.insertLatency = insertLatency;
       this.rowsUpdated = rowsUpdated;
       this.updateLatency = updateLatency;
       this.rowsDeleted = rowsDeleted;
       this.deleteLatency = deleteLatency;
       this.ioReadRequests = ioReadRequests;
       this.ioRead = ioRead;
       this.ioReadLatency = ioReadLatency;
       this.ioWriteRequests = ioWriteRequests;
       this.ioWrite = ioWrite;
       this.ioWriteLatency = ioWriteLatency;
       this.ioMiscRequests = ioMiscRequests;
       this.ioMiscLatency = ioMiscLatency;
       this.innodbBufferAllocated = innodbBufferAllocated;
       this.innodbBufferData = innodbBufferData;
       this.innodbBufferFree = innodbBufferFree;
       this.innodbBufferPages = innodbBufferPages;
       this.innodbBufferPagesHashed = innodbBufferPagesHashed;
       this.innodbBufferPagesOld = innodbBufferPagesOld;
       this.innodbBufferRowsCached = innodbBufferRowsCached;
    }
   
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public long getRowsFetched() {
        return this.rowsFetched;
    }
    
    public void setRowsFetched(long rowsFetched) {
        this.rowsFetched = rowsFetched;
    }
    public long getFetchLatency() {
        return this.fetchLatency;
    }
    
    public void setFetchLatency(long fetchLatency) {
        this.fetchLatency = fetchLatency;
    }
    public long getRowsInserted() {
        return this.rowsInserted;
    }
    
    public void setRowsInserted(long rowsInserted) {
        this.rowsInserted = rowsInserted;
    }
    public long getInsertLatency() {
        return this.insertLatency;
    }
    
    public void setInsertLatency(long insertLatency) {
        this.insertLatency = insertLatency;
    }
    public long getRowsUpdated() {
        return this.rowsUpdated;
    }
    
    public void setRowsUpdated(long rowsUpdated) {
        this.rowsUpdated = rowsUpdated;
    }
    public long getUpdateLatency() {
        return this.updateLatency;
    }
    
    public void setUpdateLatency(long updateLatency) {
        this.updateLatency = updateLatency;
    }
    public long getRowsDeleted() {
        return this.rowsDeleted;
    }
    
    public void setRowsDeleted(long rowsDeleted) {
        this.rowsDeleted = rowsDeleted;
    }
    public long getDeleteLatency() {
        return this.deleteLatency;
    }
    
    public void setDeleteLatency(long deleteLatency) {
        this.deleteLatency = deleteLatency;
    }
    public BigDecimal getIoReadRequests() {
        return this.ioReadRequests;
    }
    
    public void setIoReadRequests(BigDecimal ioReadRequests) {
        this.ioReadRequests = ioReadRequests;
    }
    public BigDecimal getIoRead() {
        return this.ioRead;
    }
    
    public void setIoRead(BigDecimal ioRead) {
        this.ioRead = ioRead;
    }
    public BigDecimal getIoReadLatency() {
        return this.ioReadLatency;
    }
    
    public void setIoReadLatency(BigDecimal ioReadLatency) {
        this.ioReadLatency = ioReadLatency;
    }
    public BigDecimal getIoWriteRequests() {
        return this.ioWriteRequests;
    }
    
    public void setIoWriteRequests(BigDecimal ioWriteRequests) {
        this.ioWriteRequests = ioWriteRequests;
    }
    public BigDecimal getIoWrite() {
        return this.ioWrite;
    }
    
    public void setIoWrite(BigDecimal ioWrite) {
        this.ioWrite = ioWrite;
    }
    public BigDecimal getIoWriteLatency() {
        return this.ioWriteLatency;
    }
    
    public void setIoWriteLatency(BigDecimal ioWriteLatency) {
        this.ioWriteLatency = ioWriteLatency;
    }
    public BigDecimal getIoMiscRequests() {
        return this.ioMiscRequests;
    }
    
    public void setIoMiscRequests(BigDecimal ioMiscRequests) {
        this.ioMiscRequests = ioMiscRequests;
    }
    public BigDecimal getIoMiscLatency() {
        return this.ioMiscLatency;
    }
    
    public void setIoMiscLatency(BigDecimal ioMiscLatency) {
        this.ioMiscLatency = ioMiscLatency;
    }
    public BigDecimal getInnodbBufferAllocated() {
        return this.innodbBufferAllocated;
    }
    
    public void setInnodbBufferAllocated(BigDecimal innodbBufferAllocated) {
        this.innodbBufferAllocated = innodbBufferAllocated;
    }
    public BigDecimal getInnodbBufferData() {
        return this.innodbBufferData;
    }
    
    public void setInnodbBufferData(BigDecimal innodbBufferData) {
        this.innodbBufferData = innodbBufferData;
    }
    public BigDecimal getInnodbBufferFree() {
        return this.innodbBufferFree;
    }
    
    public void setInnodbBufferFree(BigDecimal innodbBufferFree) {
        this.innodbBufferFree = innodbBufferFree;
    }
    public Long getInnodbBufferPages() {
        return this.innodbBufferPages;
    }
    
    public void setInnodbBufferPages(Long innodbBufferPages) {
        this.innodbBufferPages = innodbBufferPages;
    }
    public Long getInnodbBufferPagesHashed() {
        return this.innodbBufferPagesHashed;
    }
    
    public void setInnodbBufferPagesHashed(Long innodbBufferPagesHashed) {
        this.innodbBufferPagesHashed = innodbBufferPagesHashed;
    }
    public Long getInnodbBufferPagesOld() {
        return this.innodbBufferPagesOld;
    }
    
    public void setInnodbBufferPagesOld(Long innodbBufferPagesOld) {
        this.innodbBufferPagesOld = innodbBufferPagesOld;
    }
    public BigDecimal getInnodbBufferRowsCached() {
        return this.innodbBufferRowsCached;
    }
    
    public void setInnodbBufferRowsCached(BigDecimal innodbBufferRowsCached) {
        this.innodbBufferRowsCached = innodbBufferRowsCached;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.schemaTableStatisticsWithBufferId) ) return false;
		 X.schemaTableStatisticsWithBufferId castOther = ( X.schemaTableStatisticsWithBufferId ) other; 
         
		 return ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && (this.getRowsFetched()==castOther.getRowsFetched())
 && (this.getFetchLatency()==castOther.getFetchLatency())
 && (this.getRowsInserted()==castOther.getRowsInserted())
 && (this.getInsertLatency()==castOther.getInsertLatency())
 && (this.getRowsUpdated()==castOther.getRowsUpdated())
 && (this.getUpdateLatency()==castOther.getUpdateLatency())
 && (this.getRowsDeleted()==castOther.getRowsDeleted())
 && (this.getDeleteLatency()==castOther.getDeleteLatency())
 && ( (this.getIoReadRequests()==castOther.getIoReadRequests()) || ( this.getIoReadRequests()!=null && castOther.getIoReadRequests()!=null && this.getIoReadRequests().equals(castOther.getIoReadRequests()) ) )
 && ( (this.getIoRead()==castOther.getIoRead()) || ( this.getIoRead()!=null && castOther.getIoRead()!=null && this.getIoRead().equals(castOther.getIoRead()) ) )
 && ( (this.getIoReadLatency()==castOther.getIoReadLatency()) || ( this.getIoReadLatency()!=null && castOther.getIoReadLatency()!=null && this.getIoReadLatency().equals(castOther.getIoReadLatency()) ) )
 && ( (this.getIoWriteRequests()==castOther.getIoWriteRequests()) || ( this.getIoWriteRequests()!=null && castOther.getIoWriteRequests()!=null && this.getIoWriteRequests().equals(castOther.getIoWriteRequests()) ) )
 && ( (this.getIoWrite()==castOther.getIoWrite()) || ( this.getIoWrite()!=null && castOther.getIoWrite()!=null && this.getIoWrite().equals(castOther.getIoWrite()) ) )
 && ( (this.getIoWriteLatency()==castOther.getIoWriteLatency()) || ( this.getIoWriteLatency()!=null && castOther.getIoWriteLatency()!=null && this.getIoWriteLatency().equals(castOther.getIoWriteLatency()) ) )
 && ( (this.getIoMiscRequests()==castOther.getIoMiscRequests()) || ( this.getIoMiscRequests()!=null && castOther.getIoMiscRequests()!=null && this.getIoMiscRequests().equals(castOther.getIoMiscRequests()) ) )
 && ( (this.getIoMiscLatency()==castOther.getIoMiscLatency()) || ( this.getIoMiscLatency()!=null && castOther.getIoMiscLatency()!=null && this.getIoMiscLatency().equals(castOther.getIoMiscLatency()) ) )
 && ( (this.getInnodbBufferAllocated()==castOther.getInnodbBufferAllocated()) || ( this.getInnodbBufferAllocated()!=null && castOther.getInnodbBufferAllocated()!=null && this.getInnodbBufferAllocated().equals(castOther.getInnodbBufferAllocated()) ) )
 && ( (this.getInnodbBufferData()==castOther.getInnodbBufferData()) || ( this.getInnodbBufferData()!=null && castOther.getInnodbBufferData()!=null && this.getInnodbBufferData().equals(castOther.getInnodbBufferData()) ) )
 && ( (this.getInnodbBufferFree()==castOther.getInnodbBufferFree()) || ( this.getInnodbBufferFree()!=null && castOther.getInnodbBufferFree()!=null && this.getInnodbBufferFree().equals(castOther.getInnodbBufferFree()) ) )
 && ( (this.getInnodbBufferPages()==castOther.getInnodbBufferPages()) || ( this.getInnodbBufferPages()!=null && castOther.getInnodbBufferPages()!=null && this.getInnodbBufferPages().equals(castOther.getInnodbBufferPages()) ) )
 && ( (this.getInnodbBufferPagesHashed()==castOther.getInnodbBufferPagesHashed()) || ( this.getInnodbBufferPagesHashed()!=null && castOther.getInnodbBufferPagesHashed()!=null && this.getInnodbBufferPagesHashed().equals(castOther.getInnodbBufferPagesHashed()) ) )
 && ( (this.getInnodbBufferPagesOld()==castOther.getInnodbBufferPagesOld()) || ( this.getInnodbBufferPagesOld()!=null && castOther.getInnodbBufferPagesOld()!=null && this.getInnodbBufferPagesOld().equals(castOther.getInnodbBufferPagesOld()) ) )
 && ( (this.getInnodbBufferRowsCached()==castOther.getInnodbBufferRowsCached()) || ( this.getInnodbBufferRowsCached()!=null && castOther.getInnodbBufferRowsCached()!=null && this.getInnodbBufferRowsCached().equals(castOther.getInnodbBufferRowsCached()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + (int) this.getRowsFetched();
         result = 37 * result + (int) this.getFetchLatency();
         result = 37 * result + (int) this.getRowsInserted();
         result = 37 * result + (int) this.getInsertLatency();
         result = 37 * result + (int) this.getRowsUpdated();
         result = 37 * result + (int) this.getUpdateLatency();
         result = 37 * result + (int) this.getRowsDeleted();
         result = 37 * result + (int) this.getDeleteLatency();
         result = 37 * result + ( getIoReadRequests() == null ? 0 : this.getIoReadRequests().hashCode() );
         result = 37 * result + ( getIoRead() == null ? 0 : this.getIoRead().hashCode() );
         result = 37 * result + ( getIoReadLatency() == null ? 0 : this.getIoReadLatency().hashCode() );
         result = 37 * result + ( getIoWriteRequests() == null ? 0 : this.getIoWriteRequests().hashCode() );
         result = 37 * result + ( getIoWrite() == null ? 0 : this.getIoWrite().hashCode() );
         result = 37 * result + ( getIoWriteLatency() == null ? 0 : this.getIoWriteLatency().hashCode() );
         result = 37 * result + ( getIoMiscRequests() == null ? 0 : this.getIoMiscRequests().hashCode() );
         result = 37 * result + ( getIoMiscLatency() == null ? 0 : this.getIoMiscLatency().hashCode() );
         result = 37 * result + ( getInnodbBufferAllocated() == null ? 0 : this.getInnodbBufferAllocated().hashCode() );
         result = 37 * result + ( getInnodbBufferData() == null ? 0 : this.getInnodbBufferData().hashCode() );
         result = 37 * result + ( getInnodbBufferFree() == null ? 0 : this.getInnodbBufferFree().hashCode() );
         result = 37 * result + ( getInnodbBufferPages() == null ? 0 : this.getInnodbBufferPages().hashCode() );
         result = 37 * result + ( getInnodbBufferPagesHashed() == null ? 0 : this.getInnodbBufferPagesHashed().hashCode() );
         result = 37 * result + ( getInnodbBufferPagesOld() == null ? 0 : this.getInnodbBufferPagesOld().hashCode() );
         result = 37 * result + ( getInnodbBufferRowsCached() == null ? 0 : this.getInnodbBufferRowsCached().hashCode() );
         return result;
   }   


}


