package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.schemaTablesWithFullTableScansId;

/**
 * X.schemaTablesWithFullTableScans generated by hbm2java
 */
public class X.schemaTablesWithFullTableScans  implements java.io.Serializable {


     private X.schemaTablesWithFullTableScansId id;

    public X.schemaTablesWithFullTableScans() {
    }

    public X.schemaTablesWithFullTableScans(X.schemaTablesWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.schemaTablesWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTablesWithFullTableScansId id) {
        this.id = id;
    }




}


