package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.schemaTableStatisticsId;

/**
 * X.schemaTableStatistics generated by hbm2java
 */
public class X.schemaTableStatistics  implements java.io.Serializable {


     private X.schemaTableStatisticsId id;

    public X.schemaTableStatistics() {
    }

    public X.schemaTableStatistics(X.schemaTableStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsId id) {
        this.id = id;
    }




}


