package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.schemaTableLockWaitsId;

/**
 * X.schemaTableLockWaits generated by hbm2java
 */
public class X.schemaTableLockWaits  implements java.io.Serializable {


     private X.schemaTableLockWaitsId id;

    public X.schemaTableLockWaits() {
    }

    public X.schemaTableLockWaits(X.schemaTableLockWaitsId id) {
       this.id = id;
    }
   
    public X.schemaTableLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableLockWaitsId id) {
        this.id = id;
    }




}


