package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.schemaIndexStatisticsId;

/**
 * X.schemaIndexStatistics generated by hbm2java
 */
public class X.schemaIndexStatistics  implements java.io.Serializable {


     private X.schemaIndexStatisticsId id;

    public X.schemaIndexStatistics() {
    }

    public X.schemaIndexStatistics(X.schemaIndexStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaIndexStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaIndexStatisticsId id) {
        this.id = id;
    }




}


