package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.sessionId;

/**
 * X.session generated by hbm2java
 */
public class X.session  implements java.io.Serializable {


     private X.sessionId id;

    public X.session() {
    }

    public X.session(X.sessionId id) {
       this.id = id;
    }
   
    public X.sessionId getId() {
        return this.id;
    }
    
    public void setId(X.sessionId id) {
        this.id = id;
    }




}


