package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.statementsWithTempTablesId;

/**
 * X.statementsWithTempTables generated by hbm2java
 */
public class X.statementsWithTempTables  implements java.io.Serializable {


     private X.statementsWithTempTablesId id;

    public X.statementsWithTempTables() {
    }

    public X.statementsWithTempTables(X.statementsWithTempTablesId id) {
       this.id = id;
    }
   
    public X.statementsWithTempTablesId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithTempTablesId id) {
        this.id = id;
    }




}


