package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.statementsWithRuntimesIn95thPercentileId;

/**
 * X.statementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentile  implements java.io.Serializable {


     private X.statementsWithRuntimesIn95thPercentileId id;

    public X.statementsWithRuntimesIn95thPercentile() {
    }

    public X.statementsWithRuntimesIn95thPercentile(X.statementsWithRuntimesIn95thPercentileId id) {
       this.id = id;
    }
   
    public X.statementsWithRuntimesIn95thPercentileId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithRuntimesIn95thPercentileId id) {
        this.id = id;
    }




}


