package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.statementsWithFullTableScansId;

/**
 * X.statementsWithFullTableScans generated by hbm2java
 */
public class X.statementsWithFullTableScans  implements java.io.Serializable {


     private X.statementsWithFullTableScansId id;

    public X.statementsWithFullTableScans() {
    }

    public X.statementsWithFullTableScans(X.statementsWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.statementsWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithFullTableScansId id) {
        this.id = id;
    }




}


