package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.statementAnalysisId;

/**
 * X.statementAnalysis generated by hbm2java
 */
public class X.statementAnalysis  implements java.io.Serializable {


     private X.statementAnalysisId id;

    public X.statementAnalysis() {
    }

    public X.statementAnalysis(X.statementAnalysisId id) {
       this.id = id;
    }
   
    public X.statementAnalysisId getId() {
        return this.id;
    }
    
    public void setId(X.statementAnalysisId id) {
        this.id = id;
    }




}


