package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.userSummaryByFileIoTypeId;

/**
 * X.userSummaryByFileIoType generated by hbm2java
 */
public class X.userSummaryByFileIoType  implements java.io.Serializable {


     private X.userSummaryByFileIoTypeId id;

    public X.userSummaryByFileIoType() {
    }

    public X.userSummaryByFileIoType(X.userSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


