package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.userSummaryId;

/**
 * X.userSummary generated by hbm2java
 */
public class X.userSummary  implements java.io.Serializable {


     private X.userSummaryId id;

    public X.userSummary() {
    }

    public X.userSummary(X.userSummaryId id) {
       this.id = id;
    }
   
    public X.userSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryId id) {
        this.id = id;
    }




}


