package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.userSummaryByFileIoId;

/**
 * X.userSummaryByFileIo generated by hbm2java
 */
public class X.userSummaryByFileIo  implements java.io.Serializable {


     private X.userSummaryByFileIoId id;

    public X.userSummaryByFileIo() {
    }

    public X.userSummaryByFileIo(X.userSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoId id) {
        this.id = id;
    }




}


