package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.waitsByHostByLatencyId;

/**
 * X.waitsByHostByLatency generated by hbm2java
 */
public class X.waitsByHostByLatency  implements java.io.Serializable {


     private X.waitsByHostByLatencyId id;

    public X.waitsByHostByLatency() {
    }

    public X.waitsByHostByLatency(X.waitsByHostByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByHostByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByHostByLatencyId id) {
        this.id = id;
    }




}


