package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.waitClassesGlobalByLatencyId;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


