package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.waitsByUserByLatencyId;

/**
 * X.waitsByUserByLatency generated by hbm2java
 */
public class X.waitsByUserByLatency  implements java.io.Serializable {


     private X.waitsByUserByLatencyId id;

    public X.waitsByUserByLatency() {
    }

    public X.waitsByUserByLatency(X.waitsByUserByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByUserByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByUserByLatencyId id) {
        this.id = id;
    }




}


