package com.echoes.DTO;
// Generated 23 Jul, 2024 8:38:26 AM by Hibernate Tools 5.0.6.Final


import com.echoes.DTO.X.waitsGlobalByLatencyId;

/**
 * X.waitsGlobalByLatency generated by hbm2java
 */
public class X.waitsGlobalByLatency  implements java.io.Serializable {


     private X.waitsGlobalByLatencyId id;

    public X.waitsGlobalByLatency() {
    }

    public X.waitsGlobalByLatency(X.waitsGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsGlobalByLatencyId id) {
        this.id = id;
    }




}


